#pragma once

#define COMBO_ONLY_FROM_LAYER 0
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

//#define ENCODERS_PAD_A { GP0 }
//#define ENCODERS_PAD_B { GP1 }
//#define ENCODER_RESOLUTION 2
